-- Contents become posts: one illustrated card (or a slot still waiting for
-- its picture) in a category, told by one character.
--   situation  "เมื่อ INTJ เจอคนโกหกต่อหน้า"; situation_no groups the same
--              scenario across characters.
--   quote      a quote with its author, drawn with one character.
-- featured_rank is the slot on the /contents magazine spread (1 = lead).

-- Admins add posts, so ids are generated from now on.
alter table public.contents
  alter column id add generated by default as identity;
select setval(
  pg_get_serial_sequence('public.contents', 'id'),
  coalesce((select max(id) from public.contents), 0) + 1,
  false
);

update public.contents set category = 'situation' where category = '16 Situations';

alter table public.contents
  alter column category set default 'situation',
  add constraint contents_category_check check (category in ('situation', 'quote')),
  add column situation_no smallint check (situation_no > 0),
  add column quote_author text,
  add column featured_rank smallint check (featured_rank between 1 and 5);

-- One post per magazine slot. The admin action clears a slot before reusing it.
create unique index contents_featured_rank_key
  on public.contents (featured_rank)
  where featured_rank is not null;

create policy "contents_delete_admin"
  on public.contents for delete
  to authenticated
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = (select auth.uid())
        and profiles.role = 'admin'
    )
  );
